### ISSUE TITLE
sudo-less docker command in docker client

### ISSUE THREAD

**Issue by thehajime** [ukontainer/dockerd-darwin#5]

**Comment by Aniketh01** [comment]
Just a suggestion apart from the creation of the user group, Do you think it would be better if we port the rootless package for darwin and use that here?

**Comment by thehajime** [comment]
I don't know exactly but rootless extension is not trivial one which involves various hardening in various places.

**Comment by thehajime** [comment]
```
    sudo chmod 666 /tmp/var/run/docker.sock
    sudo chmod 777 /tmp/var/run/
    sudo ln -s /tmp/var/run/docker.sock /var/run/docker.sock
```

This kind of permission config allows us to use `docker` command without sudo.

ref: https://github.com/ukontainer/runu/pull/2/files#diff-abf7053c9982095b16be9e6a637a619b
